/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.imgeditor;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Iverton
 */
public class Check extends javax.swing.JFrame {

    /**
     * Creates new form Check
     */
    public Check() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconeCheckFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Apply before close?");

        jButton1.setBackground(new java.awt.Color(0, 50, 102));
        jButton1.setForeground(new java.awt.Color(0, 255, 255));
        jButton1.setText("Yes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sim(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 50, 102));
        jButton2.setForeground(new java.awt.Color(0, 255, 255));
        jButton2.setText("No");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nao(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sim(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sim
        if(cod == 0){
            RGB.ApplyColor();
            meuJFrame.chk.dispose();
            verWindowClosed = false;
            
        }
        if(cod == 1){
            Filter.ApplyFilter();
            meuJFrame.chk.dispose();
            verWindowClosed = false;
        }
        if(cod == 2){
            LightShadow.ApplyLuminance();
            meuJFrame.chk.dispose();
            verWindowClosed = false;
        }
        if(cod == 3){
            HSL.ApplyHSL();
            meuJFrame.chk.dispose();
            verWindowClosed = false;
        }
        if(cod == 4){
            YIQ.ApplyYIQ();
            meuJFrame.chk.dispose();
            verWindowClosed = false;
        }
        if(cod == 5){
            MorphTransform.ApplyMorph();
            meuJFrame.chk.dispose();
            verWindowClosed = false;
        }
    }//GEN-LAST:event_Sim

    private void Nao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nao
        if(cod == 0){
            if(verWindowClosed == true){
                verWindowClosed = false;
                RGB.cancelarCheck();
                meuJFrame.chk.dispose();
            }
            else{
                RGB.cancelarCheck();
                Check.verWindowClosed = false;
                meuJFrame.chk.dispose();
                meuJFrame.AbrirExplorer();
            }
        }
        if(cod == 1){
            if(verWindowClosed == true){
                verWindowClosed = false;
                Filter.cancelarCheck();
                meuJFrame.chk.dispose();
            }
            else{
                Filter.cancelarCheck();
                Check.verWindowClosed = false;
                meuJFrame.chk.dispose();
                meuJFrame.AbrirExplorer();
            }
        }
        if(cod == 2){
            if(verWindowClosed == true){
                verWindowClosed = false;
                LightShadow.cancelarCheck();
                meuJFrame.chk.dispose();
            }
            else{
                LightShadow.cancelarCheck();
                Check.verWindowClosed = false;
                meuJFrame.chk.dispose();
                meuJFrame.AbrirExplorer();
            }
        }
        if(cod == 3){
            if(verWindowClosed == true){
                verWindowClosed = false;
                HSL.cancelarCheck();
                meuJFrame.chk.dispose();
            }
            else{
                HSL.cancelarCheck();
                Check.verWindowClosed = false;
                meuJFrame.chk.dispose();
                meuJFrame.AbrirExplorer();
            }
        }
        if(cod == 4){
            if(verWindowClosed == true){
                verWindowClosed = false;
                YIQ.cancelarCheck();
                meuJFrame.chk.dispose();
            }
            else{
                YIQ.cancelarCheck();
                Check.verWindowClosed = false;
                meuJFrame.chk.dispose();
                meuJFrame.AbrirExplorer();
            }
        }
        if(cod == 5){
            if(verWindowClosed == true){
                verWindowClosed = false;
                MorphTransform.cancelarCheck();
                meuJFrame.chk.dispose();
            }
            else{
                MorphTransform.cancelarCheck();
                Check.verWindowClosed = false;
                meuJFrame.chk.dispose();
                meuJFrame.AbrirExplorer();
            }
        }
    }//GEN-LAST:event_Nao

    public void setIconeCheckFrame(){
        try{
            Image icone = Toolkit.getDefaultToolkit().getImage("D:/BACKUP SSD/BACKUP INTERMITENTE/LIVROS DA UFERSA/PROJETOS JAVA/Image Editor/dist/ImgEditorImage.png");
            setIconImage(icone);
        }
        catch(Exception ex){        
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Check().setVisible(true);
        });
    }
    
    public static int cod;
    public static boolean verWindowClosed = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
