/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.imgeditor;

import java.awt.Image;
import java.awt.Toolkit;
import static my.imgeditor.FramePrincipal.framePrincipal;

/**
 *
 * @author Iverton
 */
public class FrameControleCheck extends javax.swing.JFrame {

    /**
     * Creates new form Check
     */
    public FrameControleCheck() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconeFrameControleCheck();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cancelar");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Aplicar alterações antes de fechar?");

        jButton1.setBackground(new java.awt.Color(0, 50, 102));
        jButton1.setForeground(new java.awt.Color(0, 255, 255));
        jButton1.setText("Sim");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sim(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 50, 102));
        jButton2.setForeground(new java.awt.Color(0, 255, 255));
        jButton2.setText("Não");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nao(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sim(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sim
        switch(codigoOperacao){
            case 0:
                    RGB.AplicarColor();
                    FramePrincipal.FrameControleCheck.dispose();
                break;
            case 1:
                    Filtros.AplicarFiltros();
                    FramePrincipal.FrameControleCheck.dispose();
                break;
            case 2:
                   LuzESombra.AplicarLuzESombra();
                    FramePrincipal.FrameControleCheck.dispose();
                break;
            case 3:
                    HSL.AplicarHSL();
                    FramePrincipal.FrameControleCheck.dispose();
                break;
            case 4:
                    YIQ.AplicarYIQ();
                    FramePrincipal.FrameControleCheck.dispose();
                break;
            case 5:
                    Morfologicas.AplicarMorfologicas();
                    FramePrincipal.FrameControleCheck.dispose();
                break;
            default: //
        }
        framePrincipal = framePrincipal.HabilitarEDesabilitarMeuJFrame(framePrincipal, true);                                 
    }//GEN-LAST:event_Sim

    private void Nao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nao
        switch(codigoOperacao){
            case 0:
                    RGB.cancelarCheck();
                    FramePrincipal.FrameControleCheck.dispose();
                break;
            case 1:
                    Filtros.cancelarCheck();
                    FramePrincipal.FrameControleCheck.dispose();
                break;
            case 2:
                   LuzESombra.cancelarCheck();
                    FramePrincipal.FrameControleCheck.dispose();
                break;
            case 3:
                    HSL.cancelarCheck();
                    FramePrincipal.FrameControleCheck.dispose();
                break;
            case 4:
                    YIQ.cancelarCheck();
                    FramePrincipal.FrameControleCheck.dispose();
                break;
            case 5:
                    Morfologicas.cancelarCheck();
                    FramePrincipal.FrameControleCheck.dispose();
                break;
            default: //
        }
        framePrincipal = framePrincipal.HabilitarEDesabilitarMeuJFrame(framePrincipal, true);
    }//GEN-LAST:event_Nao

    public void setIconeFrameControleCheck(){
        try{
            Image icone = Toolkit.getDefaultToolkit().getImage("D:/BACKUP SSD/BACKUP INTERMITENTE/LIVROS DA UFERSA/PROJETOS JAVA/Image Editor/dist/icone.png");
            setIconImage(icone);
        }
        catch(Exception ex){        
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameControleCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameControleCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameControleCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameControleCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrameControleCheck().setVisible(true);
        });
    }
    
    public static int codigoOperacao;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
